/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CareerInterest = IDL.Record({
  'areaOfExpertise' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'productInterest' : IDL.Text,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllCareerInterests' : IDL.Func([], [IDL.Vec(CareerInterest)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitCareerInterest' : IDL.Func([CareerInterest], [], []),
  'submitInquiry' : IDL.Func([Inquiry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CareerInterest = IDL.Record({
    'areaOfExpertise' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'productInterest' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllCareerInterests' : IDL.Func(
        [],
        [IDL.Vec(CareerInterest)],
        ['query'],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitCareerInterest' : IDL.Func([CareerInterest], [], []),
    'submitInquiry' : IDL.Func([Inquiry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };